BookStore/Controllers/PracticeController.cs
using BookStore.Data;
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;
using System.Security.Cryptography.X509Certificates;

namespace BookStore.Controllers
{
    public class PracticeController : Controller
    {

        private readonly ApplicationDbContext _db;

        public PracticeController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<MyPractice> objCategoryList = _db.Practice;
            return View(objCategoryList);

        }
        public IActionResult Add()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Add(MyPractice obj)
        {

            _db.Practice.Update(obj);
            _db.SaveChanges();

            return RedirectToAction("Index");

        }

        public IActionResult Edit(int? Id)
        {
            var obj = _db.Practice.Find(Id);
            return View(obj);
        }

        [HttpPost]

        public IActionResult Edit(MyPractice obj)
            
          
            {
                _db.Practice.Update(obj);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }

        public IActionResult Delete(int? Id)
        {
            var obj = _db.Practice.Find(Id);
            return View(obj);
        }

        [HttpPost]
        public IActionResult Delete(MyPractice obj)
        {
            _db.Practice.Remove(obj);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

    }

}    
        
    
 

BookStore/Views/Practice/Add.cshtml
@model MyPractice
@{
    ViewData["Title"] = "Add";
}

<h1>Add</h1>
<body style=" background-color :greenyellow">


    <form method="post" asp-controller="Practice" asp-action="Add">
        <div class="mb-3">
            <lable class="form-label">Name</lable>
            <input type="text" class="form-control" asp-for="Name" />
            <div class="mb-3">
                <lable class="form-label">Id</lable>
                <input type="number" class="form-control" asp-for="Id" />
            </div>
            <div class="mb-3">
                <lable for="for">Indian</lable>
                <input type="checkbox" id="for" asp-for="Indian" />
            </div>
            <div class="mb-3">
                <lable class="form-label">Height</lable>
                <input type="float" class="form-control" asp-for="Height" />
            </div>
            <div class="mb-3">
                <button type="submit" class="btn btn-primary" me-3>Add</button>
                </div>
        </div>
    </form>
</body>

BookStore/Views/Practice/Delete.cshtml
@model MyPractice
@{
    ViewData["Title"] = "Edit";
}

<body style=" background-color :greenyellow">

    <h1>Delete practice item </h1>

    <form method="post" asp-controller="Practice" asp-action="Delete">
        <div class="mb-3">
            <lable class="form-label">Id</lable>
            <input type="text" class="form-control" asp-for="Id" disabled />
           
            <lable class="form-label">Name</lable>
            <input type="text" class="form-control" asp-for="Name" disabled />

            <lable class="form-label">Inadian</lable>
            <input type="text" class="form-control" asp-for="Indian" disabled />

            <lable class="form-label">Height</lable>
            <input type="text" class="form-control" asp-for="Height" disabled />
           
        </div>

        <div class="mb-3">
            <button type="submit" class="btn btn-primary" me-3>Delete</button>
            <a class="btn btn-primary" asp-controller="Practice" asp-action="Index"> Back to index page </a>

        </div>
    </form>
</body>

BookStore/Views/Practice/Edit.cshtml
@model MyPractice
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>
  


<body style=" background-color :greenyellow">


    <form method="post" asp-controller="Practice" asp-action="Edit">
        <div class="mb-3">
            <lable class="form-label">Id</lable>
            <input type="number" class="form-control" asp-for="Id" />
           
            <lable class="form-label">Name</lable>
            <input type="text" class="form-control" asp-for="Name" />

            <div class="mb-3">
                <lable for="for">Indian</lable>
                <input type="checkbox" id="for" asp-for="Indian" />
            </div>

            <lable class="form-label">Height</lable>
            <input type="float" class="form-control" asp-for="Height" />

        </div>

        <div class="mb-3">
            <button type="submit" class="btn btn-primary" me-3>edit</button>
           


        </div>
    </form>
</body>


@*
    <form method="post" asp-controller="Practice" asp-action="Edit">
        <div class="mb-3">
            <lable class="form-label">Name</lable>
            <input type="text" class="form-control" asp-for="Name" />
     

            <div class="mb-3">
                <lable class="form-label">Id</lable>
                <input type="number" class="form-control" asp-for="Id" />
            </div>
            <div class="mb-3">
                <lable for="for">Indian</lable>
                <input type="checkbox" id="for" asp-for="Indian" />
            </div>
            <div class="mb-3">
                <lable class="form-label">Height</lable>
                <input type="float" class="form-control" asp-for="Height" />
             
            </div>
            <div class="mb-3">
            
                <button type="submit" class="btn btn-primary" me-3>Edit</button>
                
            </div>
        </div>
    </form>
</body>
*@

BookStore/Views/Practice/Index.cshtml
@model IEnumerable<MyPractice>
@{
    
    ViewData["Title"] = "Practice";
}

    <h1> My Practice Page</h1>
<div align="right"><a class="btn btn-primary" asp-controller="Practice" asp-action="Add"><img src="/Icons/Add.png">Add</a></div>

   
    <table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th style=" background-color:azure">
               Id
            </th>
            <th style=" background-color:azure">
               Name
            </th>
            <th style=" background-color:azure">
              Indian
             </th>
            <th style=" background-color:azure">
              Height
            </th>
        </tr>
    </thead>
    <body style=" background-color:aqua">
        @foreach(var obj in Model)
        {
        <tr>
            <td width="15%">
                    @obj.Id

            </td>
            <td width="15%">
                    @obj.Name
            </td>

            <td width="15%">
                    @obj.Indian
            </td>

            <td width="15%">
                    @obj.Height
            </td>

            <td>
                <a class="btn " asp-controller="Practice" asp-action="Edit" asp-route-id="@obj.Id"><img src="/Icons/Add.png">Edit</a>
               <a class="btn " asp-controller="Practice" asp-action="Delete" asp-route-id="@obj.Id"><img src="~/Icons/Reyansh.png" />Delete</a>
             
            </td>

        </tr>
        }
    </body>
</table>
<div>The result count is @Model.Count()</div>
  