BookStore/Controllers/CarController.cs
using Microsoft.AspNetCore.Mvc;

namespace BookStore.Controllers
{
    public class CarController : Controller
    {
        public IActionResult Bmw()
        {
            return View();
        }
    }
}

BookStore/Controllers/ManuController.cs
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace BookStore.Controllers;

public class ManuController : Controller
{
    public IActionResult Index()
    {
        var model = new ManuViewModel()
        {
            Name = "Nandhini"
        };
        return View(model);
    }
    [HttpPost]
    public IActionResult Update(ManuViewModel model)

    {       //diffirent implementation
            var name= model.Name;
        
            return RedirectToAction("Index");
        

    }

}

BookStore/Controllers/NycController.cs
using BookStore.Data;
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookStore.Controllers
{
    public class NycController : Controller
    {
        private readonly ApplicationDbContext _db;

        public NycController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<MyNyc> objCategoryList = _db.Nyc;
            return View(objCategoryList);

        }
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(MyNyc obj)
        {

            _db.Nyc.Add(obj);
            _db.SaveChanges();

            return RedirectToAction("Index");


        }
        public IActionResult Edit(int? Id)
        {
            var obj = _db.Nyc.Find(Id);
            return View(obj);
     
        }
        [HttpPost]
        public IActionResult Edit(MyNyc obj)

        {   
                _db.Nyc.Update(obj);
                _db.SaveChanges();

                return RedirectToAction("Index");
            
           
        }
    }
}

BookStore/Controllers/SchoolController.cs
using BookStore.Data;
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookStore.Controllers
{
    public class SchoolController : Controller


    {
        private readonly ApplicationDbContext _db;

        public SchoolController(ApplicationDbContext db)
        {
            _db = db;

        }
        public IActionResult Index()
        {
            return View();
        }
        

        


        //        [HttpPost]

        //      public IActionResult Add(School obj)
        //        {

        //            {
        //                ModelState.AddModelError("Name", "The displayOrder cannot exactly match the name");
        //            }
        //            if (ModelState.IsValid)
        //            {
        //                _db.Schools.Add(obj);
        //                _db.SaveChanges();

        //                return RedirectToAction("Index");
        //            }
        //            return View(obj);
        //        }
    }
}

BookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Nandhini</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookStore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow mb-3" style="background-color:turquoise">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Nandhini</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="Bmw">Car</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Voters" asp-action="Index">Voters</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Telangana" asp-action="Index">Telangana</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Village" asp-action="Index">Village</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Manu" asp-action="Index">Manu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Praveen" asp-action="Index">Praveen</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Indians" asp-action="Index">Indians</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="School" asp-action="Index">School</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Practice" asp-action="Index">Practice</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Nyc" asp-action="Index">Nyc</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>